services:
  panel:
    build:
      context: "."
      dockerfile: "./Dockerfile"
    container_name: ${CONTAINER_NAME_PANEL:-ptero}
    pull_policy: build # Portainer need it for rebuild when updating
    restart: always
    links:
      - database
      - cache
    volumes:
      - "/data/volumes/pterodactyl/prod/www/var/:/app/var/"
      - "/data/volumes/pterodactyl/prod/www/nginx/:/etc/nginx/http.d/"
      - "/data/volumes/pterodactyl/prod/www/certs/:/etc/letsencrypt/"
      - "/data/volumes/pterodactyl/prod/www/logs/:/app/storage/logs"
    env_file: stack.env
    environment:
      APP_URL: "${APP_URL:-panel.nium-heberg.fr}"
      APP_TIMEZONE: "${APP_TIMEZONE:-Europe/Paris}"
      APP_SERVICE_AUTHOR: "${APP_SERVICE_AUTHOR:-support@nium-heberg.fr}"
      MAIL_FROM: "${MAIL_FROM:-noreply@nium-heberg.fr}"
      MAIL_FROM_NAME: "${MAIL_FROM_NAME:-Nium Heberg}"
      MAIL_DRIVER: "${MAIL_DRIVER:-smtp}"
      MAIL_HOST: "${MAIL_HOST:-smtp.exemple.com}"
      MAIL_PORT: "${MAIL_PORT:-25}"
      MAIL_USERNAME: "${MAIL_USERNAME}"
      MAIL_PASSWORD: "${MAIL_PASSWORD}"
      MAIL_ENCRYPTION: "${MAIL_ENCRYPTION:-ssl}"
      DB_PASSWORD: "${DB_PASSWORD:-CHANGE_ME}"
      APP_ENV: "${APP_ENV:-production}"
      APP_ENVIRONMENT_ONLY: "${APP_ENVIRONMENT_ONLY:-false}"
      CACHE_DRIVER: "${CACHE_DRIVER:-redis}"
      SESSION_DRIVER: "${SESSION_DRIVER:-redis}"
      QUEUE_DRIVER: "${QUEUE_DRIVER:-redis}"
      REDIS_HOST: "${REDIS_HOST:-cache}"
      DB_HOST: "${DB_HOST:-databases}"
      DB_PORT: "${DB_PORT:-3306}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.panel.rule=Host(`${TRAEFIK_URL_PANEL:-panel.nium-heberg.fr}`)"
      - "traefik.http.routers.panel.entrypoints=websecure"
      - "traefik.http.routers.panel.tls=true"
      - "traefik.http.routers.panel.tls.domains[0].main=nium-heberg.fr"
      - "traefik.http.routers.panel.tls.domains[0].sans=*.nium-heberg.fr"
      - "traefik.http.routers.panelhttp.rule=Host(`${TRAEFIK_URL_PANEL:-panel.nium-heberg.fr}`)"
      - "traefik.http.routers.panelhttp.entrypoints=web"
      - "traefik.http.routers.panelhttp.middlewares=redirecttohttpspanel@docker"
      - "traefik.http.middlewares.redirecttohttpspanel.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirecttohttpspanel.redirectscheme.permanent=true"
      - "traefik.http.services.redirecttohttpspanel.loadbalancer.server.port=80"
    networks:
      - panel

  phpMyAdmin:
    image: phpmyadmin:latest
    container_name: ${CONTAINER_NAME_PMA:-ptero-PMA}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /data/volumes/pterodactyl/prod/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
      - /data/volumes/pterodactyl/prod/phpmyadmin/origin_ca_rsa_root_cloudflare.pem:/etc/mysql/origin_ca_rsa_root_cloudflare.pem
    depends_on:
      - panel
    links:
      - database
      - panel
      - NODE01-FR.NIUM-HEBERG.FR
    restart: always
    environment:
      PMA_HOSTS: ${PMA_HOSTS:-NODE01-FR.NIUM-HEBERG.FR, DATABASE}
      PMA_ABSOLUTE_URI: ${PMA_ABSOLUTE_URI:-https://phpmyadmin.nium-heberg.fr}
      UPLOAD_LIMIT: ${UPLOAD_LIMIT:-1024M}
      HIDE_PHP_VERSION: ${HIDE_PHP_VERSION:-true}
      MAX_EXECUTION_TIME: ${MAX_EXECUTION_TIME:-600}
      MEMORY_LIMIT: ${MEMORY_LIMIT:-1024M}
    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`${TRAEFIK_URL_PMA:-phpmyadmin.nium-heberg.fr}`)"
      - "traefik.http.routers.phpmyadmin.entrypoints=websecure"
      - "traefik.http.routers.phpmyadmin.tls=true"
      - "traefik.http.routers.phpmyadmin.tls.domains[0].main=nium-heberg.fr"
      - "traefik.http.routers.phpmyadmin.tls.domains[0].sans=*.nium-heberg.fr"
      - "traefik.http.routers.phpmyadminhttp.rule=Host(`${TRAEFIK_URL_PMA:-phpmyadmin.nium-heberg.fr}`)"
      - "traefik.http.routers.phpmyadminhttp.entrypoints=web"
      - "traefik.http.routers.phpmyadminhttp.middlewares=redirecttohttpsphpmyadmin@docker"
      - "traefik.http.middlewares.redirecttohttpsphpmyadmin.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirecttohttpsphpmyadmin.redirectscheme.permanent=true"
      - "traefik.http.services.redirecttohttpsphpmyadmin.loadbalancer.server.port=80"
    networks:
      - panel

  database:
    image: mariadb:10.5
    container_name: ${CONTAINER_NAME_DB:-ptero-DB-LOCAL}
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "/data/volumes/pterodactyl/prod/database:/var/lib/mysql"
    environment:
      MYSQL_PASSWORD: "${DB_PASSWORD:-CHANGE_ME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD:-root}"
      MYSQL_DATABASE: "${MYSQL_DATABASE:-panel}"
      MYSQL_USER: "${MYSQL_USER:-pterodactyl}"
    networks:
      - panel
  
  NODE01-FR.NIUM-HEBERG.FR:
    image: mariadb:10.5
    container_name: ${CONTAINER_NAME_DB_CLIENTS:-ptero-DB-CLIENTS}
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - "/data/volumes/pterodactyl/prod/database-clients:/var/lib/mysql"
      - "/data/volumes/pterodactyl/prod/init.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD:-root}"
    networks:
      - panel

  cache:
    image: redis:alpine
    container_name: ${CONTAINER_NAME_CACHE:-ptero-CACHE}
    restart: always
    networks:
      - panel

networks:
  panel:
    name: ${NAME_NETWORK:-public_wan}
    external: true